{
 "title": "Comparison_Dashboard Copy",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "measurement_name", "query": "${VAR_MEASUREMENT_NAME}" },
   {
    "name": "test",
    "label": "Test Name",
    "query": "SHOW TAG VALUES FROM \"requestsRaw\" WITH KEY=\"testName\""
   },
   {
    "name": "runId1",
    "label": "Run Id1",
    "query": "SHOW TAG VALUES FROM \"requestsRaw\" WITH KEY=\"runId\""
   },
   {
    "name": "runId2",
    "label": "Run Id2",
    "query": "SHOW TAG VALUES FROM \"requestsRaw\" WITH KEY=\"runId\""
   }
  ]
 },
 "panels": [
  {
   "title": "Success Rate (RunId 1)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (1-sum(\"errorCount\")/count(\"responseTime\"))*100 as SuccessRate FROM \"requestsRaw\" WHERE \"runId\"=~ /$runId1/ AND testName =~ /$test/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Success Rate (RunId 2)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (1-sum(\"errorCount\")/count(\"responseTime\"))*100 as SuccessRate FROM \"requestsRaw\" WHERE \"runId\"=~ /$runId2/ AND testName =~ /$test/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Run#1 Test Name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"nodeName\") AS \"Test Name\" FROM \"requestsRaw\" WHERE runId=~/$runId1/"
    }
   ]
  },
  {
   "title": "Overall Summary - RunId 1",
   "type": "table",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(responseTime) as Count, mean(responseTime) as Avg, percentile( responseTime, 99) as \"99%\", ((sum(errorCount)/count(responseTime))*100) as \"Error%\" FROM \"requestsRaw\" where runId=~ /$runId1/  AND testName=~ /$test/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Run#2 Test Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"nodeName\") AS \"Test Name\" FROM \"requestsRaw\" WHERE runId=~/$runId2/"
    }
   ]
  },
  {
   "title": "Overall Summary - RunId 2",
   "type": "table",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(responseTime) as Count, mean(responseTime) as Avg, percentile( responseTime, 99) as \"99%\", ((sum(errorCount)/count(responseTime))*100) as \"Error%\" FROM \"requestsRaw\" where runId=~ /$runId2/  AND testName=~ /$test/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RunId 1",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT min(\"responseTime\") as \"Min\", max(\"responseTime\") as \"Max\", sum(\"responseTime\")/count(\"responseTime\") as \"Avg\",count(\"responseTime\") as \"Total Passed\", percentile( responseTime, 99) as \"99%\" FROM $measurement_name WHERE testName=~ /$test/ AND runId=~ /$runId1/ AND (errorCount=0) GROUP BY requestName",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(responseTime) as Total FROM $measurement_name where testName=~ /$test/ AND runId=~ /$runId1/  GROUP BY \"requestName\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(responseTime) as Failed FROM $measurement_name where errorCount>0  AND  runId=~ /$runId1/  AND testName=~ /$test/ GROUP BY \"requestName\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RunId 2",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT min(\"responseTime\") as \"Min\", max(\"responseTime\") as \"Max\", sum(\"responseTime\")/count(\"responseTime\") as \"Avg\",count(\"responseTime\") as \"Total Passed\", percentile( responseTime, 99) as \"99%\" FROM $measurement_name WHERE testName=~ /$test/ AND runId=~ /$runId2/ AND (errorCount=0) GROUP BY requestName",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(responseTime) as Total FROM $measurement_name where testName=~ /$test/ AND runId=~ /$runId2/  GROUP BY \"requestName\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(responseTime) as Failed FROM $measurement_name where errorCount>0 AND  runId=~ /$runId2/  AND testName=~ /$test/ GROUP BY \"requestName\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Response Time - RunId 1",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_requestName (Run Id1)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(responseTime) as Avg FROM \"requestsRaw\" where runId=~ /$runId1/  AND testName=~ /$test/ GROUP BY \"runId\", \"requestName\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Response Time - RunId 2",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_requestName (Run Id2)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(responseTime) as Avg FROM \"requestsRaw\" where runId=~ /$runId2/  AND testName=~ /$test/ GROUP BY \"runId\", \"requestName\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Comparison Summary (RunId 2 - RunId 1)",
   "type": "table",
   "description": "This table gives the comparison between two runs (RunId 2 - RunId 1). Those in green text shows performance improvement and those in red shows performance degradation",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(responseTime) as Count, mean(responseTime) as Avg,percentile( responseTime, 99) as \"99 %\",(sum(errorCount)/count(responseTime)) as \"Error Rate\" FROM \"requestsRaw\" where runId=~ /$runId1/ AND testName=~ /$test/ GROUP BY \"requestName\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(responseTime) as Count, mean(responseTime) as Avg,percentile( responseTime, 99) as \"99 %\",(sum(errorCount)/count(responseTime)) as \"Error Rate\" FROM \"requestsRaw\" where runId=~ /$runId2/ AND testName=~ /$test/ GROUP BY \"requestName\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}